# Generated by Django 5.1 on 2024-12-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_page_url', models.URLField(blank=True, null=True)),
                ('company_logo_url', models.URLField(blank=True, null=True)),
                ('employment_type', models.CharField(max_length=50)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('details_page_url', models.URLField(blank=True, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('easy_apply', models.BooleanField(default=False)),
                ('posted_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
        ),
    ]
