# Generated by Django 5.1 on 2024-12-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
